### ISSUE TITLE
Ограничение ввода диапазона чисел в поле профиля

### ISSUE THREAD

**Issue by Pegalet** [plechev-64/wp-recall#5]
При создании/редактировании числового поля (`<input type="number">`) в профиле пользователя дать возможность в админке задания минимального и максимального числа (атрибуты min и max). Было бы не плохо так же ограничеть выбор даты, заданным диапазоном в админке для поля "Дата".

**Comment by plechev-64** [comment]
решено добавлением нового типа поля - runner
